when@dev:
    monolog:
        handlers:
            google_calendar:
                type: stream
                path: "%kernel.logs_dir%/google_calendar.log"
                level: debug
                channels: [app]

when@prod:
    monolog:
        handlers:
            google_calendar:
                type: stream
                path: "%kernel.logs_dir%/google_calendar.log"
                level: info
                channels: [app]
