# Routes for Google Calendar Backend Controller

google_calendar_auth:
    path: /contao/google-calendar-auth
    controller: FourAngles\ContaoGoogleCalendarBundle\Controller\GoogleCalendarBackendController::authAction

google_calendar_callback:
    path: /contao/google-calendar-callback
    controller: FourAngles\ContaoGoogleCalendarBundle\Controller\GoogleCalendarBackendController::oauthCallbackAction

google_calendar_manual_sync:
    path: /contao/google-calendar-sync
    controller: FourAngles\ContaoGoogleCalendarBundle\Controller\GoogleCalendarBackendController::syncAction

google_calendar_sync_all:
    path: /contao/google-calendar-sync-all
    controller: FourAngles\ContaoGoogleCalendarBundle\Controller\GoogleCalendarBackendController::syncAllAction

google_calendar_import_events:
    path: /contao/google-calendar-import-events
    controller: FourAngles\ContaoGoogleCalendarBundle\Controller\GoogleCalendarBackendController::importEventsAction

google_calendar_export_events:
    path: /contao/google-calendar-export-events
    controller: FourAngles\ContaoGoogleCalendarBundle\Controller\GoogleCalendarBackendController::exportEventsAction
